//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareHouseUapa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public Productos(string codigo, int cantidad, string descripcion, int id, string localizacion, int precio)
        {
            this.codigo = codigo;
            this.cantidad = cantidad;
            this.descripcion = descripcion;
            this.id = id;
            this.localizacion = localizacion;
            this.precio = precio;
        }

        public Productos()
        {
        }

        public int id { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public int precio { get; set; }
        public int cantidad { get; set; }
        public string localizacion { get; set; }
    }
}
